// src/redux/reducers/convoReducer.ts

import { createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the initial state
export interface ConvoState {
  transcribedText: string;
  conversation: string;
}

const initialState: ConvoState = {
  transcribedText: "",
  conversation: "",
};

// Create a slice of the convo reducer using createSlice
const convoSlice = createSlice({
  name: "convo",
  initialState,
  reducers: {
    updateTranscribedText(state, action: PayloadAction<string>) {
      state.transcribedText = action.payload;
    },
    addSystemMessage(state, action: PayloadAction<string>) {
      state.conversation += `System: ${action.payload}\n`;
    },
    addPatientMessage(state, action: PayloadAction<string>) {
      state.conversation += `Patient: ${action.payload}\n`;
    },
    updateConversation(state, action: PayloadAction<string>) {
      state.conversation = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const {
  updateTranscribedText,
  addSystemMessage,
  addPatientMessage,
  updateConversation,
} = convoSlice.actions;

// Export the reducer
export default convoSlice.reducer;
