name: Deploy ClinicViews.com sub-apps to Pages

on:
    push:
        branches: ["manipulate"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Setup pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Setup Pages
              uses: actions/configure-pages@v5
              with:
                  static_site_generator: next
            - name: Install dependencies
              run: |
                  pnpm install
                  pnpm list
            - name: Run change script
              run: |
                  node --trace-warnings build.ts
              env:
                  GITHUB_PAGES: true
                  NODE_ENV: production
            - name: Build Next.js app
              run: |
                  pnpm run build
              env:
                  GITHUB_PAGES: true
                  NODE_ENV: production
            - name: List output directory
              run: ls -R out
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./out

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
